sidus_eav_model:
    families:
        Capacity:
            attributeAsLabel: capacityCode
            attributeAsIdentifier: capacityCode
            attributes:
                capacityCode:
                    type: string_identifier

                requiredTechnologies:
                    type: autocomplete_data_selector
                    multiple: true
                    form_options:
                        family: Technology
