sidus_eav_model:
    families:
        Capacity:
            attributeAsLabel: capacityCode
            attributeAsIdentifier: capacityCode
            attributes:
                capacityCode:
                    unique: true
                    required: true

                requiredTechnologies:
                    type: autocomplete_data
                    multiple: true
                    form_options:
                        family: Technology
