sidus_eav_model:
    families:
        Character:
            attributeAsLabel: fullName
            attributes:
#                - coordinate
#                - fullName
#                - dateOfBirth
#                - alignment
#                - player
#                - level
#                - deity
#                - homeland
#                - size # Class of size
#                - gender
#                - height
#                - weight
#                - hair
#                - eyes
#                - class
#                - race
#
#                # Characteristics
#                - strength
#                - dexterity
#                - constitution
#                - intelligence
#                - wisdom
#                - charisma
#
#                - currentHP # Current level of hitpoints
#                - maxHP # Maximum number of hitpoint
#                - skills # List of skills and level
#                - feats # List of special abilities
#                - effects # List of active effects, starting time and their duration
#
#                - equipment
#                - gearSlots # Embed ?
##                    Armor: suits of armor.
##                    Belts: belts and girdles.
##                    Body: robes and vestments.
##                    Chest: mantles, shirts, and vests.
##                    Eyes: eyes, glasses, and goggles.
##                    Feet: boots, shoes, and slippers.
##                    Hands: gauntlets and gloves.
##                    Head: circlets, crowns, hats, helms, and masks.
##                    Headband: headbands and phylacteries.
##                    Neck: amulets, brooches, medallions, necklaces, periapts, and scarabs.
##                    Ring (up to two): rings.
##                    Shield: shields.
##                    Shoulders: capes and cloaks.
##                    Wrist: bracelets and bracers.
#
#
