sidus_eav_model:
    families:
        Climate:
            attributeAsLabel: climateCode
            attributeAsIdentifier: climateCode
            attributes:
              - climateCode
              - description
              # Juste des idées pour aider à la génération auto et à des calculs de récoltes ou autre
              - temperatureAverage
              - temperatureMin
              - temperatureMax
              - humidityAverage
              - humidityMin
              - humidityMax
              - waterPercentage

    attributes:
        climateCode:
            required: true
            unique: true
        # In C°
        temperatureAverage:
            type: decimal
        temperatureMin:
            type: decimal
        temperatureMax:
            type: decimal
        # In mm of rain per year : @todo change me ?
        humidityAverage:
            type: decimal
        humidityMin:
            type: decimal
        humidityMax:
            type: decimal
        # As a global percentage land/water
        waterPercentage:
            type: decimal

        # Relations
        climate:
            type: autocomplete_data
            form_options:
                family: Climate
