sidus_eav_model:
    families:
        Coordinated:
            instantiable: false
            attributeAsLabel: x
            attributes:
              - x
              - y
              - world

    attributes:
        x:
            type: integer
            required: true
        y:
            type: integer
            required: true

        # relations
        coordinate:
            type: embed
            form_options:
                family: Coordinate
