sidus_eav_model:
    families:
        GameResource:
            attributeAsLabel: resourceCode
            attributeAsIdentifier: resourceCode
            attributes:
                resourceCode:
                    type: string_identifier

        GameResourceQuantity:
            attributeAsLabel: resource
            attributes:
                resource:
                    type: autocomplete_data_selector
                    form_options:
                        family: GameResource
                quantity:
                    type: decimal
