sidus_eav_model:
    families:
        Player:
            attributeAsLabel: label
            attributes:
                label:
                    required: true

                worlds:
                    type: autocomplete_data_selector
                    multiple: true
                    form_options:
                        family: World

                technologies:
                    type: autocomplete_data_selector
                    multiple: true
                    form_options:
                        family: Technology

                resourceQuantities:
                    type: embed
                    multiple: true
                    form_options:
                        family: GameResourceQuantity
