sidus_eav_model:
    families:
        Resource:
            attributeAsLabel: resourceCode
            attributeAsIdentifier: resourceCode
            attributes:
                resourceCode:
                    required: true
                    unique: true

        ResourceQuantity:
            attributeAsLabel: resource
            attributes:
                resource:
                    type: autocomplete_data
                    form_options:
                        family: Resource
                quantity:
                    type: decimal
