sidus_eav_model:
    families:
        Resource:
            attributeAsLabel: resourceCode
            attributeAsIdentifier: resourceCode
            attributes:
              - resourceCode

        ResourceQuantity:
            attributeAsLabel: resource
            attributes:
              - resource
              - quantity

    attributes:
        resourceCode:
            required: true
            unique: true
        quantity:
            type: decimal

        resourceQuantity:
            type: embed
            form_options:
                family: ResourceQuantity
        resourceQuantities:
            type: embed
            multiple: true
            form_options:
                family: ResourceQuantity

        # Relations
        resource:
            type: autocomplete_data
            form_options:
                family: Resource
        resources:
            type: autocomplete_data
            multiple: true
            form_options:
                family: Resource
