sidus_eav_model:
    families:
        Technology:
            attributeAsLabel: technologyCode
            attributeAsIdentifier: technologyCode
            attributes:
                technologyCode:
                    unique: true
                    required: true

                requiredTechnologies:
                    type: autocomplete_data
                    multiple: true
                    form_options:
                        family: Technology

                scienceCost:
                    type: integer
                    required: true

                unlockedCapacities:
                    type: autocomplete_data
                    multiple: true
                    form_options:
                        family: Capacity
