sidus_admin:
    fallback_template: CleverAgeEAVManagerAdminBundle:Base
    configurations:
        configuration:
            controller: CleverAgeEAVManagerAdminBundle:Data
            entity: '%sidus_data_class%'
            prefix: /configuration
            default_form_type: sidus_tabbed_data
            actions:
                index:
                    path:     /
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                edit:
                    path:     /{familyCode}/{id}/edit
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                datagrid: data
                families:
                    Climate: ~
                    Resource: ~
                    City: ~
