sidus_admin:
    configurations:
        configuration:
            controller: '%eav.controller%'
            entity: '%sidus_data_class%'
            prefix: /configuration
            actions:
                index:
                    path:     /
                list:
                    path:     /{familyCode}/list
                read:
                    path:     /{familyCode}/{id}/read
                    form_type: '%eav_form.type%'
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/{id}/edit
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                datagrid: data
                families:
                    Climate: ~
                    GameResource: ~
                    City: ~
