services:
    bluebear.loader.world_map:
        class: BlueBear\WorldBrowserBundle\Loader\WorldMapLoader
        arguments:
            - '@doctrine'
            - '@sidus_eav_model.family.registry'

    bluebear.generator.world:
        class: BlueBear\WorldBrowserBundle\Generator\WorldGenerator
        arguments:
            - '@doctrine'
            - '@sidus_eav_model.family.registry'
