parameters:
    blue_bear_world_browser.generator.world_map.class: BlueBear\WorldBrowserBundle\Generator\WorldMapGenerator

services:
    blue_bear_world_browser.generator.world_map:
        class: '%blue_bear_world_browser.generator.world_map.class%'

