services:
    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor }

    monolog.formatter.standard:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%](%%extra.ip%%) %%channel%%.%%level_name%%:\n  %%message%%\n  %%context%%\n\n"
