sidus_admin:
    fallback_template: CleverAgeEAVManagerAdminBundle:Base
    configurations:
        world:
            controller: CleverAgeEAVManagerAdminBundle:Data
            entity: '%sidus_data_class%'
            prefix: /world
            default_form_type: sidus_tabbed_data
            actions:
                list:
                    path:     /list
                    defaults: {family: World}
                create:
                    path:     /create
                    defaults: {family: World}
                edit:
                    path:     /{id}/edit
                    defaults: {family: World}
                delete:
                    path:     /{id}/delete
                    defaults: {family: World}

        configuration:
            controller: CleverAgeEAVManagerAdminBundle:Data
            entity: '%sidus_data_class%'
            prefix: /configuration
            default_form_type: sidus_tabbed_data
            actions:
                index:
                    path:     /
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                edit:
                    path:     /{familyCode}/{id}/edit
                delete:
                    path:     /{familyCode}/{id}/delete
            options:
                families:
                    - Climate
                    - Resource
