sidus_eav_model:
    families:
        Image:
            attributeAsLabel: title
            attributes:
                - title
                - image
                - link
                - tags
        Document:
            attributeAsLabel: title
            attributes:
                - title
                - pages
                - fileSize
                - documentType
                - document

    attributes:
        image:
            group: content
            type: image

        document:
            group: content
            type: document

        link:
            group: content
        tags:
            group: content
            multiple: true

        pages:
            group: qualification
            type: integer
        fileSize:
            group: qualification
            type: integer
            form_options:
                disabled: true
        documentType:
            group: qualification
            form_options:
                disabled: true
