sidus_eav_data_grid:
    configurations:
        # Configuration Example
        world:
            family: World
            parent: data
            filter_config:
                sortable:
                    - id
                    - label
                fields:
                    label: ~
                    climate:
                        type: autocomplete_data
            columns:
                worldCode:
                    label: "code/seed"
                label:
                    template: "CleverAgeEAVManagerAdminBundle:Base:clickable.column.html.twig"
                preview:
                    template: "BlueBearWorldBrowserBundle:World:world.preview.html.twig"
                climate: ~
                resourceQuantities: ~
                actions:
                    template: "CleverAgeEAVManagerAdminBundle:Data:list.row.actions.html.twig"
