imports:
    - { resource: parameters.yml }

     # Default parameters
    - { resource: parameters/* }

    # Default configuration for EAV Manager
    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }

    # Defining all application configuration
    - { resource: application/* }

    # EAV Manager specific configuration

    # Admins
    - { resource: admin/* }

    # Datagrids
    - { resource: datagrid/* }

    # Model
    - { resource: model/* }
