imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: model/application.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    resources_dir: %kernel.root_dir%/data/resources
    import_dir: %kernel.root_dir%/data/import
    import_downloads_dir: %import_dir%/Mediasactu-telechargement/livres_blancs
    mailer_sender: {'no-reply@bluebear.fr': 'Admin BlueBear'}

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%", en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - SidusEAVBootstrapBundle:Form:fields.html.twig
            - SidusFilterBundle:Form:fields.html.twig
            - SidusDataGridBundle:Form:fields.html.twig
            - CleverAgeEAVManagerLayoutBundle:Form:form.fields.html.twig
            - CleverAgeEAVManagerSecurityBundle:Form:form.fields.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        ### !!!! WARNING !!!!
        # If you add your own LayoutBundle that extends this one, you will have to re-declare all assetic blocks in your templates !
        - CleverAgeEAVManagerLayoutBundle
        - BlueBearLayoutBundle
    node: "%node_path%"
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%node_uglifyjs_path%"
        uglifycss:
            bin: "%node_uglifycss_path%"
    assets:
        map1:
            input: "%kernel.root_dir%/../web/assets/jquery/jquery.min.map"
            output: js/jquery.min.map
        src1:
            input: "%kernel.root_dir%/../web/assets/jquery/jquery.js"
            output: js/jquery.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            sidus_family:
                class: Sidus\EAVModelBundle\Doctrine\Types\FamilyType
                commented: true

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mopa_bootstrap:
    form:
        render_required_asterisk: true
        render_optional_text: false

fos_elastica:
    clients:
        default: { host: %fos_elastica.host%, port: %fos_elastica.port% }
    indexes:
        sidus:
            types:
                data:
                    mappings:
                        id: ~
                        parent: ~
                        family:
                            property_path: familyCode
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        label: ~
                    persistence:
                        driver: orm
                        model: BlueBear\EAVModelBundle\Entity\Data
                        provider: ~
                        listener:
                            insert: %elastica_enabled%
                            update: %elastica_enabled%
                            delete: %elastica_enabled%
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true

exercise_html_purifier:
    default:
        HTML.TargetBlank: true
#        AutoFormat.AutoParagraph: true
        AutoFormat.Linkify: true
        AutoFormat.RemoveEmpty: true
        AutoFormat.RemoveEmpty.RemoveNbsp: true
        AutoFormat.RemoveSpansWithoutAttributes: true
        Core.CollectErrors: false
#        HTML.AllowedElements:
#        HTML.AllowedAttributes:
        HTML.Trusted: true
        HTML.SafeIframe: true
        URI.SafeIframeRegexp: "~^(https?:)?//(www\.youtube(?:-nocookie)?\.com/embed/|player\.vimeo\.com/video/)~"
