imports:
    - { resource: parameters.yml }

     # Default parameters
    - { resource: parameters/* }

    # Default configuration for EAV Manager
    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }

    # Defining all application configuration
    - { resource: application/* }

    # EAV Manager specific configuration
    - { resource: admin/* }
    - { resource: datagrid/* }
    - { resource: model/* }
    - { resource: process/* }
