imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
            channels: ['!translation', '!event']
        file:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 10
            level: debug
            formatter: monolog.formatter.standard
        console:
            type: console
            channels: ['!event', '!doctrine', '!cache', '!translation']
