sidus_data_grid:
    configurations:
        city:
            parent: data
            query_handler:
                provider: sidus.eav
                options:
                    family: City
                sortable:
                    - id
                    - label
                filters:
                    label: ~
            columns:
                label:
                    template: '%clickable.template%'
                world: ~
                actions:
                    template: '%eav_datagrid.actions%'
