sidus_data_grid:
    configurations:
        world:
            parent: data
            query_handler:
                provider: sidus.eav
                options:
                    family: World
                sortable:
                    - worldCode
                    - label
                filters:
                    label: ~
                    climate:
                        type: autocomplete_data
            columns:
                worldCode:
                    label: 'code/seed'
                label:
                    template: '%clickable.template%'
                preview:
                    template: 'BlueBearWorldBrowserBundle:World:world.preview.html.twig'
                climate: ~
                resourceQuantities: ~
                actions:
                    template: '%eav_datagrid.actions%'
