sidus_eav_model:
    families:
        Coordinated:
            instantiable: false
            attributeAsLabel: x
            attributes:
                x:
                    type: integer
                    required: true
                y:
                    type: integer
                    required: true
                world:
                    type: autocomplete_data_selector
                    form_options:
                        family: World
